<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Import</name>
   <tag></tag>
   <elementGuidId>733cdcbd-0beb-4133-8688-329cdb31af0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.css-5lyhfd</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
