<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_invalid</name>
   <tag></tag>
   <elementGuidId>7c231895-0878-4642-8100-35b2829d5ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selfie-helper-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
