<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_confirmation</name>
   <tag></tag>
   <elementGuidId>993d3321-1609-45d1-b128-9a2548e3ecc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.css-1w0ym84</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
