<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_filter</name>
   <tag></tag>
   <elementGuidId>fc4a0f52-ff2f-4787-acd4-54a3aaaf44af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.css-1k0lhp1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
